### ISSUE TITLE
problem cyclic networks on test case

### ISSUE THREAD

**Issue by mkaanarici** [gcant/temporal-recovery-tree-py#3]
Aloha, running your codes on networks including cycles among some nodes,  the recursive error seems. In your test.py, if you change the barabasi albert graph values to (40,2), you will also recognize the same error. 

I would like to draw your graph and use your recovery-tree.py. I cannot truly understand your test.py. Could you add some comments on your codes so that interested people can totally understand how to use recovery-tree? 

Thanks

**Comment by jg-you** [comment]
Documentation added to test.py in PR https://github.com/gcant/temporal-recovery-tree-py/pull/4

**Comment by mkaanarici** [comment]
In fact, in the temporal_recovery.py, you already solved this problem. However, in the full_marginal.py, cycles cause problems.  I deeply looked at the code, but I was lost here :) I will convert my network to the tree as preprocessing. Thank you for your help and study.
