### ISSUE TITLE
Inference of attachment kernel

### ISSUE THREAD

**Issue by tillahoffmann** [gcant/temporal-recovery-tree-py#5]
Thanks for making the code available! Are there any examples for inferring the attachment kernel to reproduce panel (c) of figure 2 in the publication?

**Comment by gcant** [comment]
I think we did that using the C++ implementation:
[https://github.com/gstonge/fasttr](https://github.com/gstonge/fasttr)

You can use the `set_kernel` method to set a kernel and then `get_log_posterior`.  Here's an example:

```
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from fasttr import HistorySampler

def posterior(H, gamma):
    H.set_kernel(kernel=lambda k: k**gamma)
    logp = np.array(H.get_log_posterior())
    ans = logp - np.max(logp)
    return np.log(np.mean(np.exp(ans))) + np.max(logp)

G = nx.barabasi_albert_graph(1000,1)
H = HistorySampler(G)
H.sample(100)

X = np.linspace(0.85,1.15,81)
logP = np.array([posterior(H,x) for x in X])
P = np.exp(logP-np.max(logP))
P /= np.sum((X[1]-X[0])*P)

plt.figure(1) 
plt.plot(X,P)
plt.show()
```

**Comment by tillahoffmann** [comment]
That's perfect, thank you!

**Comment by tillahoffmann** [comment]
Thanks again for the speedy reply. A follow up question: how does the prior enter into the result from `get_log_posterior()`? Does the code assume a flat prior by default, and the end user can tack on penalties for custom priors?

**Comment by jg-you** [comment]
Correct -- we use a uniform prior as in Eq. (13)-(14).

**Comment by tillahoffmann** [comment]
Excellent, thank you very much.
